# development mode
version: '3.5'
services:
  avoc_discord_bot:
    image: avoc_discord_bot:${APP_VERSION:-latest}
    container_name: avoc_discord_bot
    build:
      # target: development
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./db:/app/db
    environment:
      # API_HOST: ${API_HOST:-candilib_api}
      # API_PORT: ${API_PORT:-8000}
    ports:
      - "${WEB_PORT:-8000}:8000"
    networks:
      - avoc-network
      

networks:
  avoc-network:
    name: avoc-network
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450
volumes:
  notused:
